.gitignore

This is needed to ignore the target directory that is created by `cd runtime/wasm && ./build.sh && cd ../..` (as well as any potential future target directories).

Add a leading /** to /target in .gitignore

---

Cargo.lock
consensus/Cargo.toml
consensus/src/lib.rs
runtime/src/lib.rs

This gets away the ugliness of using `DigestItem::Other` for seal.

Switch to own DigestItem impl

---

Cargo.lock
Cargo.toml
casper/Cargo.toml
casper/src/lib.rs
casper/src/randao.rs

This aims to create a generic version of the runtime, with components able to be reused outside of beacon chain environment. This PR initialize the generic RANDAO impl.

Init casper lib and generic RANDAO impl

---

casper/src/casper.rs

Split casper into context and data. Add a test that contains four validators and four epoch advancement.

Split casper function and data and add tests

---

Cargo.lock
beacon/Cargo.toml
beacon/src/primitives/authority_id.rs
beacon/src/primitives/bitfield.rs
beacon/src/primitives/signature.rs
beacon/src/primitives/version.rs
util/ssz-derive/src/hash.rs
util/ssz-derive/src/lib.rs
util/ssz/Cargo.toml
util/ssz/src/hash.rs
util/ssz/src/lib.rs

This adds a new trait `Digestible` which built on top of `digest::Digest` for hashing, instead of `hash_db::Hasher`.

Support Digest interface in ssz

---

Cargo.lock
Cargo.toml
utils/ssz-merkle/Cargo.toml
utils/ssz-merkle/src/lib.rs

Initial integration of `bm` and `ssz`. This PR introduces `ShadowVec` and `ShadowTuple`. They represent a vector or a tuple that has subsequent SimpleSerialize values, where in the binary merkle, the top-level value hash is stored. The value is then stored in a `ShadowDB` through `hash -> value` pair.

Cached SimpleSerialize: ShadowVec and ShadowTuple

---

utils/ssz/src/hash.rs
utils/ssz/src/lib.rs

`RawHashable` and `RawDigestible` puts raw hashes into struct as ssz merkle hash, without any of its internal structures. This is useful for implementing cached state.

ssz: RawHashable and RawDigestible

---

utils/ssz-derive/src/decode.rs
utils/ssz-derive/src/encode.rs
utils/ssz-derive/src/hash.rs
utils/ssz-derive/src/lib.rs
utils/ssz-derive/src/prefixable.rs
utils/ssz-derive/tests/mod.rs

This makes handling generic for ssz encoding much easier. `skip_default` allows skipping encode/decode/hashing of a field entirely. On decoding, the default value is used. `no_bound` allows skipping adding bound traits for some bounds.

ssz: add skip_default and no_bound attributes

---

Cargo.lock
beacon/src/executive/mod.rs
blockchain/Cargo.toml
blockchain/lmd-ghost/src/archive.rs
blockchain/lmd-ghost/src/lib.rs
blockchain/src/lib.rs
blockchain/src/main.rs

* Replaces `BestDepthImporter` with `ArchiveGhostImporter` in blockchain interface.
* Add necessary traits to query state internals for lmd-ghost via `JustifiableExecutor`.
* Update blockchain interface version.

Properly use lmd-ghost fork choice for blockchain interface

---

Cargo.lock
beacon/src/config.rs
beacon/src/primitives/bitfield.rs
blockchain/src/lib.rs
blockchain/src/main.rs
blockchain/src/pool.rs
crypto/src/lib.rs

When an attestation enters transaction pool, check whether the attestation data is existing. If so, we aggregate signatures to save space.

transaction-pool: aggregate signatures when attestation data is the same

---

Cargo.lock
blockchain/lmd-ghost/src/archive.rs

This fixes the ugly `ImportAction::swap`, which was there for backend type conversion.

Remove ImportAction::swap

---

Cargo.lock
blockchain/Cargo.toml
blockchain/lmd-ghost/Cargo.toml
blockchain/lmd-ghost/src/archive.rs
blockchain/src/backend.rs
blockchain/src/lib.rs
blockchain/src/main.rs
blockchain/src/rocksdb.rs

Prefer composition over inheritance for backend function separation to simplify the design.
* Underlying database defines its own "settlement" type, which can be called by an operation to commit a database transaction. This makes backend atomic, while also extensible for operations that it can support.
* End users are expected to "compose" multiple backend types that he or she wants to support for query and commitment. For convenience, the traits are defined again.

Overhaul backend interface design

---

beacon/src/executive/helpers/mod.rs
beacon/src/executive/transition/per_block/operations/attester_slashing.rs
beacon/src/executive/transition/per_block/operations/deposit.rs
beacon/src/lib.rs

Fixes #149 
Based on diff https://github.com/ethereum/eth2.0-specs/compare/v0.6.1...v0.6.3
The `full.sorted()` line looks like the only change made to spec.

Update spec from v0.6.1 to v0.6.3

---

Cargo.lock
beacon/src/config.rs
beacon/src/error.rs
beacon/src/executive/mod.rs
beacon/src/executive/transition/per_block/operations/proposer_slashing.rs
beacon/src/executive/transition/per_block/operations/transfer.rs
yamltests/Cargo.toml
yamltests/scripts/run.sh
yamltests/scripts/run_mainnet.sh
yamltests/scripts/run_minimal.sh
yamltests/src/epoch_processing.rs
yamltests/src/lib.rs
yamltests/src/main.rs
yamltests/src/operations.rs
yamltests/src/sanity.rs

This adds all operations, sanity, epoch processing tests for spec v0.6.3. You can run it with
```
cd yamltests
scripts/run.sh
```
Two workarounds are needed, and they're reported in upstream issues https://github.com/ethereum/eth2.0-specs/issues/1147 https://github.com/ethereum/eth2.0-specs/issues/1146

Update spec test to v0.6.3

---

blockchain/src/pool.rs

Fixes #148.
When there're duplicated attestation bitfields, try to find an attestation that does not have duplication and merge with it. If that's not possible, add it as a new attestation.

Handle attestation duplicated aggregation

---

.gitlab-ci.yml
beacon/src/executive/mod.rs
beacon/src/executive/transition/mod.rs
beacon/src/executive/transition/per_block/mod.rs
yamltests/src/main.rs
yamltests/src/sanity.rs

- Update test vector to v0.7.1, removing workarounds https://github.com/ethereum/eth2.0-specs/issues/1169 https://github.com/ethereum/eth2.0-specs/issues/1147 https://github.com/ethereum/eth2.0-specs/issues/1146
- Integrate test suite to CI.

Update test vectors to v0.7.1 and integrate CI

---

blockchain/src/main.rs
blockchain/src/rocksdb.rs

- Make sure on the RocksDB backend layer, nothing will panic. Errors, if happened in the DB, will be propagated. The only possible panic should be just lock poisoning.
- Create a reliable `open_or_create` for RocksDB by checking keys `KEY_HEAD` and `KEY_GENESIS`.

Reliable RocksDB error handling and `open_or_create`

---

Cargo.lock
beacon/Cargo.toml
beacon/src/config.rs
beacon/src/executive/helpers/accessors.rs
beacon/src/executive/helpers/mutators.rs
beacon/src/executive/mod.rs
beacon/src/executive/transition/per_block/header.rs
beacon/src/executive/transition/per_epoch/helpers.rs
beacon/src/lib.rs
beacon/src/primitives/mod.rs
beacon/src/types/block.rs
beacon/src/types/operation.rs
beacon/src/utils/mod.rs
beacon/src/utils/serde.rs
utils/ssz/Cargo.toml
utils/ssz/derive/Cargo.toml
utils/ssz/src/lib.rs
utils/ssz/src/series.rs
utils/ssz/src/size.rs

* Ensure all items in `ssz` and `beacon` crate have at least simple docs.
* Bump version of `ssz` to `0.2.0` and publish crate.
* Bump version of `beacon` to `0.2.0` and publish crate.

Ensure docs and publish crate for ssz and beacon

---

substrate/casper/srml/src/lib.rs
substrate/casper/template/runtime/src/lib.rs

This implements FFG slashing conditions for srml-casper.
* Attestation is changed to use validator id instead of validator index. The former is more stable across session.

srml-casper: implement slashing conditions

---

substrate/casper/primitives/src/lib.rs
substrate/casper/srml/src/lib.rs

Previously, we use block number to store where an epoch starts, and the current justified and finalized number. However, in Substrate, session can have variable length. In this PR we introduce epoch number so that it's always clearly know how many epochs the justified/finalized block is behind the current.

srml-casper: introduce epoch number

---

Cargo.lock
beacon/Cargo.toml
beacon/wasm/Cargo.lock
beacon/wasm/Cargo.toml
beacon/wasm/index.js
blockchain/Cargo.toml
utils/ssz/Cargo.toml
yamltests/ssztests/Cargo.toml

This was the cause of `U1099511627776::to_usize() == 0`. The fix is explicitly use `u64` in `bm` crate.

wasm: fix U1099511627776 exceeding u32 limit

---

beacon/src/utils/serde.rs
beacon/wasm/index.js

The `f64` parsing for json is most likely incorrect. Instead, users are expected to always quote large integers so that they can be parsing in Rust manually.
Also fixed incorrect values in example block data.

beacon, beacon-wasm: fix incorrect example block and remove f64 parsing for uint

---

beacon/wasm/Cargo.lock
beacon/wasm/Cargo.toml
beacon/wasm/src/lib.rs

This replaces `serde-json` encoding/decoding with builtin serde feature provided by `wasm-bindgen`. Should be faster compared with before.

beacon-wasm: use the builtin serde feature provided by wasm-bindgen

---

beacon/wasm/Cargo.lock
beacon/wasm/Cargo.toml

Update the `Cargo.lock` file for `beacon-wasm` and release `v0.2.3`.

beacon-wasm: update cargo lock

---

.gitmodules
Cargo.lock
beacon/src/config.rs
beacon/src/lib.rs
blockchain/lmd-ghost/Cargo.toml
blockchain/lmd-ghost/src/archive.rs
blockchain/network/messages/src/codec.rs
blockchain/network/messages/src/lib.rs
blockchain/network/src/discovery.rs
blockchain/network/src/handler.rs
blockchain/network/src/lib.rs
blockchain/src/lib.rs
blockchain/src/main.rs
blockchain/src/preset.rs

This adds basic support for syncing with Prysm's Sapphire testnet. To test this out, you will need to run a local Prysm node:
```
ocker run --rm -v $HOME/workspace/prysm-data:/data -p 4000:4000 -p 13000:13000 --name beacon-node gcr.io/prysmaticlabs/prysm/beacon-chain:latest --datadir=/data
```
Run Shasper with `--chain sapphire` flag and specify the prysm node as one of the local node to connect to.
```
RUST_BACKTRACE=1 RUST_LOG=info cargo run --release --bin shasper-blockchain -- --chain sapphire --port 3001 --libp2p-nodes /ip4/127.0.0.1/tcp/13000
```

Add Support for Prysm's Sapphire Testnet

---

blockchain/network/messages/src/lib.rs

This changes pubsub topic names to use the new format `/eth2/TopicName/TopicEncoding`.

Fix pubsub names
