runtime/src/utils.rs, runtime/src/validation.rs
rel https://github.com/ethereum/eth2.0-specs/pull/14
* Remove an unused `Never` struct.
* Add `utils::sqrt` for integer square root.
=> Define integer sqrt for reward quotient

Cargo.lock, network/src/lib.rs, runtime/Cargo.toml, runtime/src/attestation.rs, runtime/src/extrinsic.rs, runtime/src/lib.rs, runtime/src/spec/mod.rs, runtime/src/state.rs, runtime/src/system.rs, runtime/wasm/Cargo.lock, runtime/wasm/Cargo.toml, service/Cargo.toml, service/src/chain_spec.rs, service/src/lib.rs, transaction-pool/src/lib.rs, util/ssz-hash-derive/tests/mod.rs, util/ssz-hash/src/lib.rs, util/ssz/src/codec.rs
Update all current substrate deps to git HEAD.
=> Update substrate deps to git HEAD

Cargo.lock, Cargo.toml, lmd-ghost/Cargo.toml, lmd-ghost/src/lib.rs, primitives/Cargo.toml, primitives/src/lib.rs
This adds a draft implementation for LMD-GHOST fork choice rule, and it's not yet integrated. See crate docs for usage information.
=> Draft implementation for LMD-GHOST fork choice rule

consensus/src/proposer.rs, crypto/src/lib.rs, runtime/src/extrinsic.rs, runtime/src/genesis.rs, runtime/src/lib.rs, runtime/src/spec.rs, runtime/src/storage.rs, src/chain_spec.rs, src/cli.rs, src/error.rs, src/main.rs, src/service.rs
All files should have license header. Ooops!
=> Fix missing license headers

README.md
..so that there's something you can do with the client.
=> README: block authoring logic is added

Cargo.lock, consensus/src/lib.rs
Call `save` after each block import.
=> Save latest attestation info after block import

consensus/src/lib.rs
New height is parent height plus one.
=> Fix off-by-one error in is-new-best

Cargo.lock, crypto/src/lib.rs, primitives/src/attestation.rs, primitives/src/lib.rs, primitives/src/signature.rs, runtime/wasm/Cargo.lock
Add aggregate signature support via `G2`.
=> Re-introduce aggregate signature support

README.md
=> README: add install clang req.

Cargo.lock, casper/Cargo.toml, casper/src/casper.rs, casper/src/lib.rs
Add a generic Casper FFG gadget based on the new v0.1 spec.
=> Generic Casper FFG finalization and justification

casper/src/casper.rs, casper/src/lib.rs, casper/src/reward.rs
Split rewards into casper rewards and beacon rewards.
=> Casper and beacon rewards and penalities

casper/src/casper.rs, casper/src/lib.rs, casper/src/reward.rs, casper/src/store.rs
So that we have cleaner separation of store and impls.
=> Refactor casper and rewards mod

runtime/src/lib.rs
=> Fix the issue that multiple attestations got into multiple blocks

Cargo.lock, Cargo.toml, beacon/src/executive/per_block.rs, beacon/src/lib.rs, blockchain/Cargo.toml, blockchain/src/lib.rs
This PR adds a simple interface to blockchain, making it potentially possible to run full beacon node in lighter environments.
=> Add a simple interface to blockchain

Cargo.lock, beacon/src/block.rs, beacon/src/executive/mod.rs, beacon/src/executive/per_block.rs, beacon/src/lib.rs, blockchain/Cargo.toml, blockchain/src/lib.rs
Adds `UnsealedBeaconBlock` type and allow building blocks without messing with the signature field.
=> Nicer interface for block builder

Cargo.lock, Cargo.toml, blockchain/lmd-ghost/Cargo.toml, blockchain/lmd-ghost/src/lib.rs
A lightweight interface for cache, with algorithm from https://github.com/protolambda/lmd-ghost
=> Add back standalone lmd ghost interface with cache

beacon/src/config.rs, beacon/src/error.rs, beacon/src/executive/mod.rs, beacon/src/executive/transition/per_epoch/registry.rs, beacon/src/types/block.rs, blockchain/src/lib.rs, blockchain/src/main.rs
You can try this out by
```
cd blockchain && cargo run -- --author
```
=> Implement basic block authoring logic for v0.7 spec

beacon/src/executive/assignment.rs, beacon/src/executive/choice.rs, beacon/src/executive/helpers/mod.rs, beacon/src/executive/mod.rs, beacon/src/primitives/bitfield.rs, beacon/src/types/state.rs, blockchain/src/lib.rs, blockchain/src/main.rs
Based on v0.6 validator guide.
This allows local known validators to attest blocks and submit attestations.
=> Basic validator implementation

Cargo.lock, blockchain/Cargo.toml, blockchain/lmd-ghost/Cargo.toml, blockchain/lmd-ghost/src/archive.rs, blockchain/src/lib.rs, blockchain/src/main.rs, blockchain/src/rocksdb.rs
Add a rocksdb backend for beacon chain. This can be used by specifying the `--data [path]` parameter.
=> RocksDB backend

Cargo.lock, blockchain/lmd-ghost/src/archive.rs, blockchain/src/main.rs
=> Separate import lock from backend

blockchain/src/lib.rs, blockchain/src/main.rs, blockchain/src/rocksdb/backend.rs, blockchain/src/rocksdb/mod.rs, blockchain/src/rocksdb/settlement.rs
Fixes #162. Add trait `RocksState` which allows converting back and forth of a raw state together with a database handle.
=> Generalized RocksState for easier merkle node fetching in the future

blockchain/src/main.rs
In v0.8, deposit proof are with an additional depth of length mix, but our current proof generation code didn't handle it. This PR generates the additional depth proof and makes the blockchain client able to build blocks and submit attestations.
=> Handle length mix for deposit proof

Cargo.lock, beacon/Cargo.toml, beacon/src/primitives/macros.rs, blockchain/Cargo.toml, utils/ssz/Cargo.toml, yamltests/ssztests/Cargo.toml
=> dep: update bm-le to 0.10

blockchain/network/src/handler.rs, blockchain/network/src/service.rs, blockchain/src/main.rs
=> Clean up some unused imports
